CREATE TABLE vernacular_names (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vernacular_name varchar NOT NULL,
    language varchar
);

CREATE UNIQUE INDEX vernacular_names_unique_name ON vernacular_names (vernacular_name, language);


CREATE TABLE name_vernacular_names (
    name_id uuid REFERENCES names NOT NULL,
    vernacular_name_id bigint REFERENCES vernacular_names NOT NULL,
    PRIMARY KEY(name_id, vernacular_name_id)
);
COMMENT ON TABLE name_vernacular_names IS 'A through table linking vernacular names to scientific names';


CREATE VIEW common_names AS
SELECT *
FROM (
  SELECT
    taxa.*,
    array_agg(vernacular_names.vernacular_name)
      OVER (PARTITION BY scientific_name ORDER BY vernacular_names.id DESC) AS names,
    rank() OVER (PARTITION BY scientific_name ORDER BY vernacular_names.id ASC) AS window_rank
  FROM taxa
  JOIN name_vernacular_names ON taxa.name_id = name_vernacular_names.name_id
  JOIN vernacular_names ON name_vernacular_names.vernacular_name_id = vernacular_names.id
) tbl
WHERE window_rank = 1
