[package]
name = "arga-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-graphql = { version = "5.0.5", features = ["tracing", "tokio"] }
async-graphql-axum = "5.0.5"
async-trait = "0.1.64"
axum = "0.6.4"
diesel = { version = "2.0.3", features = ["uuid"] }
diesel-async = { version = "0.2.0", features = ["postgres", "bb8"] }
dotenvy = "0.15.6"
futures = "0.3.26"
heck = "0.4.1"
hyper = "0.14.23"
opentelemetry = { version = "0.18.0", features = ["metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.11.0", features = ["metrics"] }
reqwest = { version = "0.11.14", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
tokio = { version = "1.24.2", features = ["full"] }
tower-http = { version = "0.3.5", features = ["cors", "trace"] }
tracing = "0.1.37"
tracing-opentelemetry = { version = "0.18.0", features = ["metrics"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
url = "2.3.1"
uuid = { version = "1.2.2", features = ["serde"] }
