FROM arigaio/atlas:0.35.0-community
LABEL org.opencontainers.image.source="https://github.com/ARGA-Genomes/arga-backend"
LABEL org.opencontainers.image.description="A container image for running migration jobs"
LABEL org.opencontainers.image.licenses="AGPL-3.0"

WORKDIR /
ENV DATABASE_URL=postgres://localhost/arga
CMD ["migrate", "apply", "--env", "arga", "--baseline", "20250605060808"]

COPY ./core/atlas.hcl /
COPY ./core/migrations /migrations
