# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/database/schema.rs"
filter = { except_tables = ["spatial_ref_sys"] }

[migrations_directory]
dir = "migrations"
