name: Test

on:
  workflow_run:
    workflows:
      - Build image and deploy to ghcr.io
    types:
      - completed

env:
  registry: ghcr.io/arga-genomes
  image_name: backend
  image_tag: ${{ github.sha }}
  actor: ${{ github.triggering_actor }}
  repository: ${{ github.repository }}
  ref: ${{ github.ref }}
  sha: ${{ github.sha }}
  workflow: ${{ github.workflow }}
  workflow_ref: ${{ github.workflow_ref }}
  workflow_sha: ${{ github.workflow_sha }}
  run_id: ${{ github.run_id }}
  run_number: ${{ github.run_number }}
  run_attempt: ${{ github.run_attempt }}

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send published event to arga-ops
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ARGA_OPS_DEPLOY_KEY }}
          repository: arga-genomes/arga-ops
          event-type: published
          client-payload: toJson(env)
