name: Schema check
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'core/migrations/*'
      - 'core/schema.sql'
jobs:
  lint:
    services:
      # Spin up a postgres:15 container to be used as the dev-database for analysis.
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: dev
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
          version: "v0.33.1"
      - uses: ariga/atlas-action/migrate/lint@v1
        with:
          dir: 'file://core/migrations'
          dir-name: 'arga-core'
          dev-url: postgres://postgres:pass@localhost:5432/dev?sslmode=disable
