CREATE TABLE vernacular_names (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vernacular_name varchar NOT NULL,
    language varchar
);

CREATE UNIQUE INDEX vernacular_names_unique_name ON vernacular_names (vernacular_name, language);


CREATE TABLE vernacular_name_properties (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entity_id bigint REFERENCES vernacular_names NOT NULL,
    attribute_id uuid REFERENCES attributes NOT NULL,
    value_id bigint NOT NULL
);

CREATE UNIQUE INDEX vernacular_name_unique_properties ON vernacular_name_properties (entity_id, attribute_id, value_id);


CREATE TABLE properties_string (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value varchar NOT NULL
);

CREATE UNIQUE INDEX properties_string_unique_value ON properties_string (value);


CREATE TABLE name_vernacular_names (
    name_id uuid REFERENCES names NOT NULL,
    vernacular_name_id bigint REFERENCES vernacular_names NOT NULL,
    PRIMARY KEY(name_id, vernacular_name_id)
);
COMMENT ON TABLE name_vernacular_names IS 'A through table linking vernacular names to scientific names';


CREATE VIEW common_names AS
SELECT
    names.id AS id,
    vernacular_name,
    language AS vernacular_language,
    scientific_name,
    authorship as scientific_name_authorship,
    canonical_name,
    rank
FROM name_vernacular_names
JOIN vernacular_names on name_vernacular_names.vernacular_name_id = vernacular_names.id
JOIN names on name_vernacular_names.name_id = names.id;
